name: Update Recent Release

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-recent-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch latest commit info from GitHub API
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/vx-clutch/repos?per_page=100" \
            | jq '[.[] | select(.fork==false)] | map({name: .name, url: .html_url})' > repos.json

          jq -c '.[]' repos.json | while read repo; do
            name=$(echo $repo | jq -r '.name')
            url=$(echo $repo | jq -r '.url')
            commit=$(curl -s -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/vx-clutch/$name/commits?per_page=1" | jq '.[0]')
            if [ "$commit" != "null" ]; then
              date=$(echo $commit | jq -r '.commit.author.date')
              commit_url=$(echo $commit | jq -r '.html_url')
              echo "{\"name\":\"$name\",\"url\":\"$url\",\"commitDate\":\"$date\",\"commitUrl\":\"$commit_url\"}" >> commits.jsonl
            fi
          done

          if [ -f commits.jsonl ]; then
            jq -s 'sort_by(.commitDate) | reverse | .[0]' commits.jsonl > recent-release.json
          else
            echo '{"error":"No recent commits found."}' > recent-release.json
          fi

      - name: Move JSON to public directory
        run: |
          mkdir -p public
          mv recent-release.json public/recent-release.json

      - name: Commit and push recent release JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/recent-release.json
          git commit -m "Update recent release info [skip ci]" || echo "No changes to commit"
          git push 